apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-crd
  namespace: default
subjects:
- kind: ServiceAccount
  name: controller-sa
roleRef:
  kind: Role
  name: crd-watcher
  apiGroup: rbac.authorization.k8s.io