apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: crd-watcher
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["CustomResourceDefinition"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["marufeuille.dev"]
  resources: ["taskreport"]
  verbs: ["get", "watch", "list"]